import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip"

const AppFont = DM_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Kivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={AppFont.className}
      >
        <TooltipProvider>{children}</TooltipProvider>
      </body>
    </html>
  );
}
