import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip"
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import Provider from "./provider";

const AppFont = DM_Sans({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Kivo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={AppFont.className}
        >
          <Provider>
            <TooltipProvider>

              {children}

            </TooltipProvider>
          </Provider>

        </body>
      </html>
    </ClerkProvider>
  );
}
